/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.adr.mmmmm;

import java.awt.Component;
import java.awt.Frame;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author adrian
 */
public class DlgMessages extends javax.swing.JDialog {

    /**
     * Creates new form DlgMessages
     */
    public DlgMessages(Component parent) {
        super(getRootFrame(parent), true);
        setUndecorated(true);
        initComponents();
        
        
       
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put( KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE , 0), "close");
        // getRootPane().setDefaultButton(jOK);  
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put( KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "close");
        getRootPane().getActionMap().put("close", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });        
    }
    
    public void display() {
        pack();
        centerDialog();
        setVisible(true);
    }
    
    public void setMsgTitle(String title) {
        jtitle.setText(title);        
    }
    
    public void setMsgBody(String body) {
        jbody.setText(body);        
    }
    
    
    private static Frame getRootFrame(Component parent) {
        Component c = SwingUtilities.getRoot(parent);
        if (c instanceof Frame) {
            return (Frame) c;
        } else {
            return new Frame();
        }      
    }
        
    private void centerDialog() {
        int width = this.getWidth();
        int height = this.getHeight();
        Rectangle r = getParent().getBounds();
        setBounds(r.x + (r.width-width)/2, r.y + (r.height-height)/2, width, height);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jbody = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jtitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("controlShadow")), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jbody.setText("jbody");
        jbody.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 0, 0));
        jPanel2.add(jbody, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jtitle.setFont(jtitle.getFont().deriveFont(jtitle.getFont().getSize()+3f));
        jtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtitle.setText("jtitle");
        jPanel1.add(jtitle, java.awt.BorderLayout.PAGE_START);
        jPanel1.add(jSeparator1, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jbody;
    private javax.swing.JLabel jtitle;
    // End of variables declaration//GEN-END:variables
}
