/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.adr.mimame.display;

import com.adr.mimame.GamesItem;
import com.adr.mimame.GamesItemInfo;
import com.adr.mimame.JPanelIcon;
import com.adr.mimame.Main;
import java.awt.BorderLayout;
import java.awt.Component;

/**
 *
 * @author adrian
 */
public class InfoTitleImage extends javax.swing.JPanel implements GamesItemInfo {

    private JPanelIcon jicon = new JPanelIcon(480, 640);
    
    /**
     * Creates new form NewJPanel
     */
    public InfoTitleImage() {
        initComponents();
        
        jtitle1.setFont(Main.FONT_ARCADE.deriveFont(24.0f));
        jtitle2.setFont(Main.FONT_ARCADE.deriveFont(16.0f));
        add(jicon);
    }
    
    @Override
    public Component getComponent() {
        return this;
    }

    @Override
    public void renderGamesItem(GamesItem item) {
        if (item == null) {
            jtitlecontainer.setVisible(false);
            jicon.setImage(null);
        } else {
            if (item.isTitlesDefault())  {
                jtitle1.setText(item.getTitle1());
                jtitle2.setText(item.getTitle2());
                jtitlecontainer.setVisible(true);
            } else {
                jtitlecontainer.setVisible(false);
            }
            jicon.setImage(item.getTitles());
        }
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtitlecontainer = new javax.swing.JPanel();
        jtitle1 = new javax.swing.JLabel();
        jtitle2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(480, 640));
        setLayout(new java.awt.BorderLayout());

        jtitlecontainer.setBackground(java.awt.Color.black);
        jtitlecontainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(100, 10, 10, 10));
        jtitlecontainer.setLayout(new java.awt.GridLayout(0, 1));

        jtitle1.setForeground(new java.awt.Color(215, 215, 215));
        jtitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtitlecontainer.add(jtitle1);

        jtitle2.setForeground(new java.awt.Color(215, 215, 215));
        jtitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtitlecontainer.add(jtitle2);

        add(jtitlecontainer, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jtitle1;
    private javax.swing.JLabel jtitle2;
    private javax.swing.JPanel jtitlecontainer;
    // End of variables declaration//GEN-END:variables
}
